### ISSUE TITLE
Неиспользование подходящих структур

### ISSUE THREAD

**Issue by Masynchin** [BobaUbisoft17/Schedule_bot#15]
Хранить даты надо в `datetime.date`, тем более что уже импортирован модуль.

https://github.com/BobaUbisoft17/Schedule_bot/blob/68c3347a59843c08a735ac0417771d5bfeaf1655/schedule_bot/convert_text_to_image.py#L151-L190

**Comment by BobaUbisoft17** [comment]
Пожалуйста, назовите конкретные строки

**Comment by Masynchin** [comment]
https://github.com/BobaUbisoft17/Schedule_bot/blob/68c3347a59843c08a735ac0417771d5bfeaf1655/schedule_bot/convert_text_to_image.py#L29-L34

Здесь `date` имеет тип не `datetime.date`, а `str`, из-за этого последующий код должен её каждый раз парсить. В идеале `date` уже должна быть типа `datetime.date`.
